### ISSUE TITLE
Hard dependency "certutil"

### ISSUE THREAD

**Issue by dotnetCarpenter** [slavaGanzin/http2-server#11]
On linux, `http2-server --generate-cert --trust-cert` has a hard dependency on `certutil`.
This should be mentioned in the _README.md_.

```js
const trust = () => new Promise((resolve) => {
  if (!trustCert) return resolve()
  require('child_process').execSync(
    `certutil -d sql:$HOME/.pki/nssdb -A -t "P,," -n ${cert} -i ${cert}`
  )
  trusted(cert)
})
  .then(() => process.exit())
```
_generateCertificates.js_

On Ubuntu/Mint `certutil` is in the `libnss3-tools` package and **not** installed by default.

**Comment by slavaGanzin** [comment]
Good call
