### ISSUE TITLE
Naive push not working

### ISSUE THREAD

**Issue by braadworst** [slavaGanzin/http2-server#2]
If I use the push, the resources that are pushed will not load properly, in my case a css and js file. Turning of the push will work.

**Comment by slavaGanzin** [comment]
@braadworst Can you provide http2-server logs with naive push enabled?

**Comment by braadworst** [comment]
@slavaGanzin I played around with it a bit and this is what I found

running like **http2-server --log** Not sure if the logging is working only got this:

GET / 200 18.372 ms - 1833
GET /dist/styles.css 200 13.364 ms - 5581
GET /dist/main.js 200 17.931 ms - 560439
GET / 200 11.513 ms - 1833

Which looks pretty standard

## Dev Tools (Chrome)

### Headers:

Request URL:https://localhost:4443/dist/main.js
Request Method:GET
Status Code:200 
Remote Address:127.0.0.1:4443

Response Headers
status:200

Request Headers
Provisional headers are shown
Referer:https://localhost:4443/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

Weird thing is the _Provisional headers are shown_ shows a icon with an exclamation mark, but can't figure out what it means

### Response:

It is empty

**Comment by braadworst** [comment]
Looks like it is related to this, http://stackoverflow.com/questions/37088397/gcm-chrome-empty-data-response

Got this error:

http2:error:push Error: Got RST: INTERNAL_ERROR
  http2:error:push     at Stream._handleRST (/Users/braadworst/www/f1.royniels.nl/frontend/node_modules/spdy-transport/lib/spdy-transport/stream.js:280:24)
  http2:error:push     at Stream._handleFrame (/Users/braadworst/www/f1.royniels.nl/frontend/node_modules/spdy-transport/lib/spdy-transport/stream.js:126:10)
  http2:error:push     at Connection._handleFrame (/Users/braadworst/www/f1.royniels.nl/frontend/node_modules/spdy-transport/lib/spdy-transport/connection.js:326:12)
  http2:error:push     at Parser.<anonymous> (/Users/braadworst/www/f1.royniels.nl/frontend/node_modules/spdy-transport/lib/spdy-transport/connection.js:158:10)
  http2:error:push     at emitOne (events.js:96:13)
  http2:error:push     at Parser.emit (events.js:188:7)
  http2:error:push     at readableAddChunk (/Users/braadworst/www/f1.royniels.nl/frontend/node_modules/readable-stream/lib/_stream_readable.js:217:18)
  http2:error:push     at Parser.Readable.push (/Users/braadworst/www/f1.royniels.nl/frontend/node_modules/readable-stream/lib/_stream_readable.js:176:10)
  http2:error:push     at Parser.Transform.push (/Users/braadworst/www/f1.royniels.nl/frontend/node_modules/readable-stream/lib/_stream_transform.js:123:32)
  http2:error:push     at next (/Users/braadworst/www/f1.royniels.nl/frontend/node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:52:12) +5m

Cannot reproduce it to be honest... FF also is not working

**Comment by slavaGanzin** [comment]
Should be working now. Can you retest

**Comment by braadworst** [comment]
Check everything tomorrow about to sleep

**Comment by braadworst** [comment]
```Error: Got RST: PROTOCOL_ERROR
    at Stream._handleRST (/Users/braadworst/www/vehisell-frontend/node_modules/spdy-transport/lib/spdy-transport/stream.js:280:24)
    at Stream._handleFrame (/Users/braadworst/www/vehisell-frontend/node_modules/spdy-transport/lib/spdy-transport/stream.js:126:10)
    at Connection._handleFrame (/Users/braadworst/www/vehisell-frontend/node_modules/spdy-transport/lib/spdy-transport/connection.js:326:12)
    at Parser.<anonymous> (/Users/braadworst/www/vehisell-frontend/node_modules/spdy-transport/lib/spdy-transport/connection.js:158:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at readableAddChunk (/Users/braadworst/www/vehisell-frontend/node_modules/readable-stream/lib/_stream_readable.js:217:18)
    at Parser.Readable.push (/Users/braadworst/www/vehisell-frontend/node_modules/readable-stream/lib/_stream_readable.js:176:10)
    at Parser.Transform.push (/Users/braadworst/www/vehisell-frontend/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at next (/Users/braadworst/www/vehisell-frontend/node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:52:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/braadworst/.nvm/versions/node/v6.9.5/bin/node" "/Users/braadworst/.nvm/versions/node/v6.9.5/bin/npm" "run" "serve"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vehisell-frontend@1.0.0 serve: http2-server --log --proxy --http-port 8081
```

-- gzip doesn't work anymore, it is not recognised...

It all feels a bit buggy on my node 6.9.5 setup, even installing seems not to go correctly:

```
node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.9.5 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
```

Get a lot of messages when installing

```
iltorb@1.0.13 install /Users/braadworst/www/vehisell-frontend/node_modules/iltorb
```

**Comment by slavaGanzin** [comment]
You can use this key:
```-g, --compression                 enable deflate/gzip/brotli/zopfli```
