### ISSUE TITLE
Can't make it work on MacOS

### ISSUE THREAD

**Issue by andrei-cacio** [slavaGanzin/http2-server#3]
Hi, is there a way I can install `certutil` on macos? or is there an equivalent tool?

Thanks!

**Comment by slavaGanzin** [comment]
@andrei-cacio Hello
As I understand certutil is part of ```nss``` brew package:
https://docs.giantswarm.io/guides/importing-certificates/#mac-os-firefox

 I'll switch to something like https://www.npmjs.com/package/devcert
