### ISSUE TITLE
Single Page Apps and URL

### ISSUE THREAD

**Issue by maxime1992** [slavaGanzin/http2-server#4]
Hi! First of all let me say that it's the best lib to serve assets quickly over HTTP2 that I've found so far :)
Congrats :clap: !

I'd like to know if I'm missing something or not, but is it possible to have an SPA with a route that works on page reload?

I guess that you're already familiar with `http-server` which supports `--push-state` for that.

Thanks for any help :)

**Comment by slavaGanzin** [comment]
Hello. I don't know anything about pushState(even if I had read https://github.com/indexzero/http-server/issues/80).

Why you can't just use proxy argument pointing to your index page?
```
 --proxy [https://127.0.0.1:4443]  Proxies all requests which can't be resolved locally to the given url.
    e.g.: -P http://someurl.com
```

**Comment by maxime1992** [comment]
I did try that. Within my angular app, I end up with URL like that:

`http://localhost:4200/some-url`

When I start your server and reach the URL, it says "Cannot GET /some-url".

Here's how I'm launching the server:
`http2-server -P https://localhost:4443/index.html`

I also tried without, index.html but no luck either. Maybe I'm putting a wrong URL or not using -P like I should ?

**Comment by slavaGanzin** [comment]
I think this is because: ```http://localhost:4200/some-url``` is over http, and ```https://localhost:4443/index.html``` isn't. So try to disable https if you don't need it.

If your angular app serves at ```http://localhost:4200/some-url``` you should try ```http2-server --proxy http://localhost:4200 --no-ssl``` and try to open in browser: ```http://localhost:8080/some-url```.

You can review and retest(this was only way I test this before):
https://github.com/slavaGanzin/http2-server/blob/master/tests/features/08-proxy.feature
