### ISSUE TITLE
Generate cert errors out when directory already exists

### ISSUE THREAD

**Issue by Bauke** [slavaGanzin/http2-server#7]
```
ssl:certificate:error Error: EEXIST: file already exists, mkdir 'certs'
ssl:certificate:error     at Object.mkdirSync (fs.js:764:3)
```

Not really a big problem, but I think it shouldn't error out when the directory already exists. It should just say something like "'certs' directory already exists, skipping generation" and maybe provide a "force" option of sorts so it overwrites already existing.

**Comment by slavaGanzin** [comment]
@Bauke Thanks for notice. Fixed
